### ISSUE TITLE
请做一个yae，非常感谢🙏

### ISSUE THREAD

**Issue by abyss1103** [yejunjie10311031/GI-Assets-homo#1]
请把胸部和乳头以及缝和屁眼轮廓做出来，现在的yae看得太难受了

**Comment by abyss1103** [comment]
我知道您专门做男的，可目前的3Dmogito的yae看起来真的无语，希望能做出来放到zeroka的模组里，衷心感谢

**Comment by yejunjie10311031** [comment]
好吧,明天做

**Comment by abyss1103** [comment]
> 好吧,明天做

再次感谢🙏

**Comment by yejunjie10311031** [comment]
> > 好吧,明天做
> 
> 再次感谢🙏

做好了,你看看怎么样
[YaeMod.zip](https://github.com/yejunjie10311031/GI-Assets-homo/files/9051548/YaeMod.zip)
![Genshin Impact 2022_7_6 12_10_01](https://user-images.githubusercontent.com/62139629/177467651-c71085c9-5440-4967-b9c6-153dac7d0dfd.png)

**Comment by abyss1103** [comment]
> > > 好吧,明天做
> > 
> > 
> > 再次感谢🙏
> 
> 做好了,你看看怎么样 [YaeMod.zip](https://github.com/yejunjie10311031/GI-Assets-homo/files/9051548/YaeMod.zip) ![Genshin Impact 2022_7_6 12_10_01](https://user-images.githubusercontent.com/62139629/177467651-c71085c9-5440-4967-b9c6-153dac7d0dfd.png)

胸有点小了

**Comment by abyss1103** [comment]
> > > 好吧,明天做
> > 
> > 
> > 再次感谢🙏
> 
> 做好了,你看看怎么样 [YaeMod.zip](https://github.com/yejunjie10311031/GI-Assets-homo/files/9051548/YaeMod.zip) ![Genshin Impact 2022_7_6 12_10_01](https://user-images.githubusercontent.com/62139629/177467651-c71085c9-5440-4967-b9c6-153dac7d0dfd.png)

脖子那边看得……而且胸没变化，更之前一样，胸是连在一起的，而且下面也没做好

**Comment by abyss1103** [comment]
我以为可以用blender可以做出像MMD那样状态，现在来看估计还不行，非常感谢🙏
